---
apiversion: storage.k8s.io/v1
Kind: StorageClass
Metadata:
  name: redis-storageclass
Provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
Reclaimpolicy: Retain
Allowvolumeexpansion: true
Mountoptions:
  - debug
Volumebindingmode: Immediate


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-volume
spec:
  capacity:
   storage: 5Gi
  accessModes:
   - ReadWriteOnce
  storageClassName: slow


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
    storage: 8Gi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: caching
  labels:
    app: redis
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: redisinsight
    template:
      metadata:
        labels:
          app: redisinsight
      spec:
        containers:
        - name:  redisinsight
          image: redislabs/redisinsight:1.9.0
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          volumeMounts:
          - name: db
            mountPath: /db
          ports:
          - containerPort: 8001
            protocol: TCP
        volumes:
        - name: db
          persistentVolumeClaim:
            claimName: redis-pv-claim